#!/bin/sh

# Find an available python command because recent systems install only
# "python3" instead of "python" by default. Note that """ means a block
# comment on Python, and ":" means no-op on shell script.

""":"
for cmd in python3 python; do
  $cmd -V > /dev/null 2>&1 && exec $cmd $0 "$@"
done

echo "Cannot find Python interpreter!"
exit 1
":"""

import sys
import json
import struct
import subprocess


def getMessage():
    if sys.version_info[0] < 3:
        rawLength = sys.stdin.read(4)
    else:
        rawLength = sys.stdin.buffer.read(4)
    if len(rawLength) == 0:
        sys.exit(0)
    messageLength = struct.unpack('@I', rawLength)[0]
    message = sys.stdin.read(messageLength)
    return json.loads(message)


mode = getMessage()
if mode != "active" and mode != "inactive":
    sys.exit(0)

# Sometimes ibus-set-input-mode fails due to unstability of IBus.
# To avoid it, retry on the error.
for i in range(1, 5):
    try:
        subprocess.call(["/usr/local/bin/ibus-set-input-mode", mode])
        break
    except CalledProcessError as e:
        if e.returncode != 1:
           break
